name: Build and Deploy to Cloud Run1

on:
    push:
        branches:
            - master

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: ${{ secrets.RUN_PROJECT }}
    RUN_REGION: us-east1
    SERVICE_NAME: super-simple-service

jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest

        steps:
          - name: Login
            uses: google-github-actions/setup-gcloud@v0
            with:
              project_id: ${{ secrets.RUN_PROJECT }}
              service_account_email: ${{ secrets.SA_EMAIL }}
              service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

          - name: Checkout
            uses: actions/checkout@v2

          - name: gcloud Set up
            run: |
                gcloud config set project $PROJECT_ID

          - name: Build
            run: |
                gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
                
          - name: Deploy
            run: |
                gcloud run deploy $SERVICE_NAME \
                  --region $RUN_REGION \
                  --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                  --platform managed